# Generated by Django 2.1.14 on 2021-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reason_of_admission',
            field=models.CharField(blank=True, db_column='reasonOfAdmission', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='referral_case',
            field=models.BooleanField(blank=True, db_column='referralCase', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='regular_checkup',
            field=models.BooleanField(blank=True, db_column='regularCheckup', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='type_of_sickness',
            field=models.TextField(blank=True, db_column='typeOdSickness', null=True),
        ),
    ]
