# Generated by Django 2.1.14 on 2021-01-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_auto_20210115_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='employerId',
            field=models.ForeignKey(blank=True, db_column='employerSSFID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributor', to='sosys.Employer'),
        ),
    ]
