# Generated by Django 2.1.14 on 2021-01-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_auto_20210118_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='employerId',
            field=models.CharField(blank=True, db_column='employerSSFID', max_length=30, null=True),
        ),
    ]
