# Generated by Django 2.1.14 on 2021-01-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_auto_20210119_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='employerId',
        ),
    ]
