# Generated by Django 2.1.14 on 2021-01-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0005_auto_20210120_1039'),
        ('claim', '0006_remove_claim_employerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_employer', to='sosys.Employer'),
        ),
    ]
