# Generated by Django 2.1.14 on 2021-01-27 10:49

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_healthfacilitycatchment_healthfacilitylegalform_healthfacilitymutation_healthfacilitysublevel'),
        ('claim', '0008_auto_20210122_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='discharge_summary',
            field=models.TextField(blank=True, db_column='dischargeSummary', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='discharge_type',
            field=models.CharField(blank=True, db_column='dischargeType', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_by_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refered_claim', to='claim.Claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_flag',
            field=models.BooleanField(db_column='referFlag', default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_to_date',
            field=core.fields.DateField(blank=True, db_column='referToDate', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_to_health_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='HFID_REFER_TO', to='location.HealthFacility'),
        ),
    ]
