# Generated by Django 2.1.14 on 2021-01-31 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0007_auto_20210130_1550'),
        ('claim', '0009_auto_20210127_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='hf_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='hf_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='hf_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_hf_bank', to='sosys.Bank'),
        ),
        migrations.AddField(
            model_name='claim',
            name='hf_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_hf_branch', to='sosys.BankBranch'),
        ),
    ]
