# Generated by Django 2.1.14 on 2021-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_auto_20210131_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='hf_account_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='hf_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
