# Generated by Django 2.1.14 on 2021-02-01 08:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0011_auto_20210131_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='reason_of_admission',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='referral_case',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='regular_checkup',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='type_of_sickness',
        ),
        migrations.AddField(
            model_name='claim',
            name='accident_description',
            field=models.TextField(blank=True, db_column='AccidentDescription', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='capability',
            field=models.CharField(blank=True, db_column='Capability', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='condition_of_wound',
            field=models.CharField(blank=True, db_column='ConditionOfWound', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='dead_certificate_attachment',
            field=models.BinaryField(blank=True, db_column='DeadCertificateAttachment', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='dead_date',
            field=models.DateField(blank=True, db_column='DeadDate', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='dead_reason',
            field=models.TextField(blank=True, db_column='DeadReason', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='dead_time',
            field=models.TimeField(blank=True, db_column='DeadTime', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='family_sickness',
            field=models.CharField(blank=True, db_column='FamilySickness', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='injured_body_part',
            field=models.TextField(blank=True, db_column='InjuredBodyPart', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_dead',
            field=models.CharField(blank=True, db_column='IsDead', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='reason_of_sickness',
            field=models.CharField(blank=True, db_column='ReasonOfSickness', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_from_date',
            field=models.DateField(blank=True, db_column='ReferFromDate', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_from_health_facility',
            field=models.CharField(blank=True, db_column='ReferFromHealthFacility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='discharge_summary',
            field=models.TextField(blank=True, db_column='DischargeSummary', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='discharge_type',
            field=models.CharField(blank=True, db_column='DischargeType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='refer_flag',
            field=models.BooleanField(db_column='ReferFlag', default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='refer_to_date',
            field=core.fields.DateField(blank=True, db_column='ReferToDate', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='refer_to_health_facility',
            field=models.CharField(blank=True, db_column='Refer', max_length=255, null=True),
        ),
    ]
