# Generated by Django 2.1.14 on 2021-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0014_claim_is_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='is_admitted',
            field=models.BooleanField(db_column='IsAdmitted', default=False),
        ),
    ]
