# Generated by Django 2.1.14 on 2021-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0016_auto_20210202_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='capability',
            field=models.CharField(blank=True, db_column='Capability', max_length=5, null=True),
        ),
    ]
