# Generated by Django 2.1.14 on 2021-02-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0017_auto_20210202_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='family_sickness',
        ),
        migrations.AddField(
            model_name='claim',
            name='cancer',
            field=models.CharField(blank=True, db_column='Cancer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='diabetes',
            field=models.CharField(blank=True, db_column='Diabetes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='heart_attack',
            field=models.CharField(blank=True, db_column='HeartAttack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='high_bp',
            field=models.CharField(blank=True, db_column='HighBp', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='hiv',
            field=models.CharField(blank=True, db_column='HIV', max_length=255, null=True),
        ),
    ]
