# Generated by Django 2.1.14 on 2021-02-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_auto_20210202_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='refer_to_health_facility',
            new_name='refer_to_hospital',
        ),
    ]
