# Generated by Django 2.1.14 on 2021-02-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0019_auto_20210202_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='check_attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='check_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='scheme_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='scheme_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
