# Generated by Django 2.1.14 on 2021-02-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0022_auto_20210214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='refer_from_hf_other',
            field=models.CharField(blank=True, db_column='ReferFromHfOther', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_to_hf_other',
            field=models.CharField(blank=True, db_column='ReferToHFOther', max_length=255, null=True),
        ),
    ]
