# Generated by Django 2.1.14 on 2021-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0023_auto_20210214_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimattachment',
            name='documentFrom',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
