# Generated by Django 2.1.14 on 2021-02-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0024_auto_20210216_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'managed': True},
        ),
    ]
