# Generated by Django 2.1.14 on 2021-02-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '__first__'),
        ('claim', '0025_auto_20210219_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_product', to='product.Product'),
        ),
    ]
