# Generated by Django 2.1.14 on 2021-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0026_claim_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
