# Generated by Django 2.1.14 on 2021-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0027_claim_is_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='is_disable',
            field=models.CharField(blank=True, db_column='is_disable', max_length=255, null=True),
        ),
    ]
