# Generated by Django 2.1.14 on 2021-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0029_auto_20210301_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='follow_up_date',
            field=models.DateField(blank=True, db_column='FollowUpDate', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rest_period',
            field=models.IntegerField(blank=True, db_column='RestPeriod', null=True),
        ),
    ]
