# Generated by Django 2.1.14 on 2021-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0031_auto_20210303_1236'),
    ]
