# Generated by Django 2.1.14 on 2021-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0031_auto_20210303_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(db_column='ClaimCode', max_length=60),
        ),
    ]
