# Generated by Django 2.1.14 on 2021-03-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0032_auto_20210322_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_for',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
