# Generated by Django 2.1.14 on 2021-03-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0032_auto_20210322_1654'),
        ('claim', '0032_auto_20210322_1444'),
    ]

    operations = [
    ]
