# Generated by Django 2.1.14 on 2021-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0033_claim_claim_for'),
        ('claim', '0033_merge_20210323_0831'),
    ]

    operations = [
    ]
