# Generated by Django 2.1.14 on 2021-01-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='AddressId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='sosys.Address'),
        ),
    ]
