# Generated by Django 2.1.14 on 2021-01-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0002_auto_20210111_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insureeemployer',
            old_name='E_SSID',
            new_name='E_SS',
        ),
        migrations.RemoveField(
            model_name='insureeemployer',
            name='p_ssid',
        ),
    ]
