# Generated by Django 2.1.14 on 2021-01-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0004_confirmationtype_education_profession_relation'),
        ('sosys', '0003_auto_20210119_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureeemployer',
            name='p_ss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.Insuree'),
        ),
    ]
