# Generated by Django 2.1.14 on 2021-01-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_auto_20210127_1049'),
        ('sosys', '0005_auto_20210120_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRecommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommender_ssid', models.CharField(blank=True, max_length=14, null=True)),
                ('recommender_post', models.CharField(blank=True, max_length=50, null=True)),
                ('recommender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recommender_contact', models.CharField(blank=True, max_length=14, null=True)),
                ('recommend_date', models.CharField(blank=True, max_length=10, null=True)),
                ('recommend_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('recommend_attachment', models.BinaryField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('present_after_case', models.BooleanField(default=False)),
                ('last_present_date', models.CharField(blank=True, max_length=10, null=True)),
                ('present_after_acc_date', models.CharField(blank=True, max_length=10, null=True)),
                ('present_before_app', models.BooleanField(default=False)),
                ('acc_date_time', models.DateTimeField(blank=True, null=True)),
                ('work_shift', models.CharField(blank=True, max_length=10, null=True)),
                ('inform_date', models.CharField(blank=True, max_length=10, null=True)),
                ('heal_time', models.CharField(blank=True, max_length=10, null=True)),
                ('leave_from_date', models.CharField(blank=True, max_length=10, null=True)),
                ('leave_to_date', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.CharField(blank=True, max_length=10, null=True)),
                ('accident_place', models.CharField(blank=True, max_length=10, null=True)),
                ('tool_description', models.TextField(blank=True, null=True)),
                ('work_during_acc', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_head', to='claim.Claim')),
            ],
        ),
    ]
