# Generated by Django 2.1.14 on 2021-01-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0006_claimrecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecommend',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_head', to='claim.Claim', unique=True),
        ),
    ]
