# Generated by Django 2.1.14 on 2021-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0007_auto_20210130_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrecommend',
            name='acc_date_time',
        ),
        migrations.AddField(
            model_name='claimrecommend',
            name='acc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrecommend',
            name='acc_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
