# Generated by Django 2.1.14 on 2021-01-31 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0008_auto_20210131_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecommend',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_head', to='claim.Claim'),
        ),
    ]
