# Generated by Django 2.1.14 on 2021-02-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0010_auto_20210201_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sch_name', models.CharField(max_length=100)),
                ('sch_name_eng', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('use_by', models.CharField(max_length=5)),
            ],
        ),
    ]
