# Generated by Django 2.1.14 on 2021-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0011_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecommend',
            name='recommend_attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
