# Generated by Django 2.1.14 on 2021-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0012_auto_20210202_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureeemployer',
            name='JoinDate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insureeemployer',
            name='Post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insureeemployer',
            name='TerminatedDate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
