# Generated by Django 2.1.14 on 2021-02-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0014_auto_20210209_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDocumentsMaster',
            fields=[
                ('id', models.AutoField(db_column='DocId', primary_key=True, serialize=False)),
                ('DocName', models.CharField(db_column='DocumentName', max_length=255)),
                ('UseBy', models.CharField(db_column='UseBy', max_length=15)),
                ('EnterDate', models.DateField(db_column='EnterDate', default='2021-02-11')),
                ('Status', models.BooleanField(db_column='Status', default=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
