# Generated by Django 2.1.14 on 2021-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0015_claimdocumentsmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocumentsmaster',
            name='EnterDate',
            field=models.DateField(db_column='EnterDate', default='2021-02-13'),
        ),
    ]
