# Generated by Django 2.1.14 on 2021-02-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_healthfacilitycatchment_healthfacilitylegalform_healthfacilitymutation_healthfacilitysublevel'),
        ('sosys', '0016_auto_20210213_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='HFBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(db_column='AccountName', max_length=60)),
                ('account_number', models.CharField(db_column='AccountNumber', max_length=30)),
                ('purpose', models.CharField(max_length=15)),
                ('bank_id', models.ForeignKey(db_column='BankId', on_delete=django.db.models.deletion.DO_NOTHING, to='sosys.Bank')),
                ('branch_id', models.ForeignKey(db_column='BranchId', on_delete=django.db.models.deletion.DO_NOTHING, to='sosys.BankBranch')),
                ('health_facility', models.ForeignKey(db_column='HF', on_delete=django.db.models.deletion.DO_NOTHING, to='location.HealthFacility')),
            ],
        ),
    ]
