# Generated by Django 2.1.14 on 2021-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0017_hfbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='hfbankdetails',
            name='validity_from',
            field=models.DateTimeField(blank=True, db_column='ValidityFrom', null=True),
        ),
        migrations.AddField(
            model_name='hfbankdetails',
            name='validity_to',
            field=models.DateTimeField(blank=True, db_column='ValidityTo', null=True),
        ),
        migrations.AlterField(
            model_name='claimdocumentsmaster',
            name='EnterDate',
            field=models.DateField(db_column='EnterDate', default='2021-02-14'),
        ),
    ]
