# Generated by Django 2.1.14 on 2021-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0018_auto_20210214_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocumentsmaster',
            name='EnterDate',
            field=models.DateField(db_column='EnterDate'),
        ),
    ]
