# Generated by Django 2.1.14 on 2021-02-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0019_auto_20210214_1020'),
        ('sosys', '0016_auto_20210214_1019'),
    ]

    operations = [
    ]
