# Generated by Django 2.1.14 on 2021-02-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0020_merge_20210214_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocumentsmaster',
            name='EnterDate',
            field=models.DateField(db_column='EnterDate'),
        ),
    ]
