# Generated by Django 2.1.14 on 2021-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0021_auto_20210214_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecommend',
            name='work_shift',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
