# Generated by Django 2.1.14 on 2021-02-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0022_auto_20210215_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfbankdetails',
            name='health_facility',
            field=models.ForeignKey(db_column='HF', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_bank_detail', to='location.HealthFacility'),
        ),
    ]
