# Generated by Django 2.1.14 on 2021-02-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0025_auto_20210224_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
