# Generated by Django 2.1.14 on 2021-02-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '__first__'),
        ('sosys', '0026_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sch_name', models.CharField(max_length=100)),
                ('sch_name_eng', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subProduct', to='product.Product')),
            ],
        ),
    ]
