# Generated by Django 2.1.14 on 2021-03-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0027_subproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecommend',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_recommendation', to='claim.Claim'),
        ),
    ]
