# Generated by Django 2.1.14 on 2021-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0028_auto_20210303_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
