# Generated by Django 2.1.14 on 2021-03-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0029_subproduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='p_ssid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_set', to='insuree.Insuree'),
        ),
    ]
