# Generated by Django 2.1.14 on 2021-03-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0030_auto_20210322_1444'),
        ('sosys', '0030_auto_20210322_1654'),
    ]

    operations = [
    ]
