# Generated by Django 2.1.14 on 2021-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosys', '0031_merge_20210323_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranch',
            name='CIPSBranchId',
            field=models.IntegerField(default=1),
        ),
    ]
